### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by sergej-js** [chipslays/litegram#1]
PHP Fatal error:  Uncaught Error: Call to undefined function bot() in /var/www/www-root/data/www/mydomain/lite:12
Stack trace:
#0 {main}
  thrown in /var/www/www-root/data/www/mydomain/lite on line 12
  
 Выдается такая ошибка не знаю как ее решить.
 Пробовал разные версии php, но ошибка везде та же
 
There is such an error I do not know how to solve it.
I tried different versions of php, but the error is the same everywhere

**Comment by chipslays** [comment]
Подключили зависимости? 
```
require __DIR__ . '/vendor/autoload.php';
```

И полный код можно увидеть?

**Comment by sergej-js** [comment]
> Подключили зависимости?
> 
> ```
> require __DIR__ . '/vendor/autoload.php';
> ```
> 
> И полный код можно увидеть?

Я создал проект по документации, отредактировал конфиг и попытался запустить, но выдало ошибку выше

**Comment by chipslays** [comment]
> > Подключили зависимости?
> > ```
> > require __DIR__ . '/vendor/autoload.php';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > И полный код можно увидеть?
> 
> Я создал проект по документации, отредактировал конфиг и попытался запустить, но выдало ошибку выше

Очень странно, почему тогда хелпер `bot()` не подцепился.
Вы создали с помощью [Litegram Project](https://github.com/chipslays/litegram-project)?

Попробуйте вместо `bot($config)` использовать `\Litegram\Bot::getInstance()->auth($config);`

**Comment by sergej-js** [comment]
> > > Подключили зависимости?
> > > ```
> > > require __DIR__ . '/vendor/autoload.php';
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > И полный код можно увидеть?
> > 
> > 
> > Я создал проект по документации, отредактировал конфиг и попытался запустить, но выдало ошибку выше
> 
> Очень странно, почему тогда хелпер `bot()` не подцепился.
> Вы создали с помощью [Litegram Project](https://github.com/chipslays/litegram-project)?
> 
> Попробуйте вместо `bot($config)` использовать `\Litegram\Bot::getInstance()->auth($config);`

Да, я создал проект с помощью Litegram Project

Сделал как вы просили:

PHP Fatal error:  Uncaught Error: Class 'Litegram\Bot' not found in /var/www/www-root/data/www/domain/lite:12
Stack trace:
#0 {main}
  thrown in /var/www/www-root/data/www/domain/lite on line 12

**Comment by sergej-js** [comment]
Вы тут? @chipslays

**Comment by chipslays** [comment]
> > > > Подключили зависимости?
> > > > ```
> > > > require __DIR__ . '/vendor/autoload.php';
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > И полный код можно увидеть?
> > > 
> > > 
> > > Я создал проект по документации, отредактировал конфиг и попытался запустить, но выдало ошибку выше
> > 
> > 
> > Очень странно, почему тогда хелпер `bot()` не подцепился.
> > Вы создали с помощью [Litegram Project](https://github.com/chipslays/litegram-project)?
> > Попробуйте вместо `bot($config)` использовать `\Litegram\Bot::getInstance()->auth($config);`
> 
> Да, я создал проект с помощью Litegram Project
> 
> Сделал как вы просили:
> 
> PHP Fatal error: Uncaught Error: Class 'Litegram\Bot' not found in /var/www/www-root/data/www/domain/lite:12
> Stack trace:
> #0 {main}
> thrown in /var/www/www-root/data/www/domain/lite on line 12

Выполните `composer install ` из папки с проектом, такое ощущение, что зависимости не установились (в папке `vendor/chipslays` скорее всего нет папки `litegram`).

Больше пока что идей никаких нет.

**Comment by sergej-js** [comment]
К сожалению не помогло. Написало, что обновления не требуются, но я в ручную проверил репозиторий и там половины файлов просто не скачалось. Я скачал в ручную, настроил, установил зависимости и теперь их в разы больше, чем было в первый раз, но теперь другая ошибка выскочила при попытке миграции:

PHP Fatal error:  Trait method __call_function has not been applied, because there are collisions with other trait methods on Litegram\Bot in /var/www/www-root/data/www/domain/SuperDuperBot/vendor/chipslays/litegram/src/Bot.php on line 27

**Comment by chipslays** [comment]
Папка `vendor` должна была создаться автоматически, достаточно было создать проект командой:

```bash
composer create-project chipslays/litegram-project SuperDuperBot
```

Рекомендую использовать PHP 7.4.

Попробуйте тогда добавить файлы в проект из этого архива, перед этим удалив старые.
[vendor.zip](https://github.com/chipslays/litegram/files/7237506/vendor.zip)

**Comment by sergej-js** [comment]
> Папка `vendor` должна была создаться автоматически, достаточно было создать проект командой:
> 
> ```shell
> composer create-project chipslays/litegram-project SuperDuperBot
> ```
> 
> Рекомендую использовать PHP 7.4.
> 
> Попробуйте тогда добавить файлы в проект из этого архива, перед этим удалив старые.
> [vendor.zip](https://github.com/chipslays/litegram/files/7237506/vendor.zip)

`[27.09.2021 19:42:07] [longpoll] [info] Long-polling started...
PHP Fatal error:  Uncaught Error: Call to undefined function Litegram\Traits\Http\curl_init() in /var/www/www-root/data/www/pay-id615482374.ru/SuperDuperBot/vendor/chipslays/litegram/src/Traits/Http/Request.php:77
Stack trace:
#0 /var/www/www-root/data/www/pay-id615482374.ru/SuperDuperBot/vendor/chipslays/litegram/src/Traits/Http/Request.php(25): Litegram\Bot->initTelegramCurlClient()
#1 /var/www/www-root/data/www/pay-id615482374.ru/SuperDuperBot/vendor/chipslays/litegram/src/Traits/Handlers.php(61): Litegram\Bot->api()
#2 /var/www/www-root/data/www/pay-id615482374.ru/SuperDuperBot/bot/core/handlers/longpoll.php(34): Litegram\Bot->longpoll()
#3 {main}
  thrown in /var/www/www-root/data/www/pay-id615482374.ru/SuperDuperBot/vendor/chipslays/litegram/src/Traits/Http/Request.php on line 77`

**Comment by chipslays** [comment]
> Call to undefined function Litegram\Traits\Http\curl_init()

https://stackoverflow.com/questions/6382539/call-to-undefined-function-curl-init

**Comment by chipslays** [comment]
Если будут вопросы по [Litegram Project](https://github.com/chipslays/litegram-project), задавайте их [здесь](https://github.com/chipslays/litegram-project/issues).
